### ISSUE TITLE
Not getting the intro text anymore

### ISSUE THREAD

**Issue by samolapraga** [smooch/smooch-wordpress#13]
Hi, since the latest changes we're not getting the customized intro text that i've written in the plugin settings. Can you help? Thanks!

**Comment by ruess** [comment]
Any update on this issue? I'm getting the same thing

**Comment by Go-Fred** [comment]
Thanks for reporting it. We'll investigate!

**Comment by firelite** [comment]
Hi, I'm getting this same issue again for the latest version.  When I modify the intro text, it does not change on in the chat box, but everything else does.  Can you have a look?

**Comment by firelite** [comment]
Actually, this might just be because the Smooch Wordpress plugin in the WordPress repo isn't hasn't been updated to the latest.  Not sure if this plugin is the same (and maintained by the same people) as the one up in WordPress.
