### ISSUE TITLE
Chat Window Propriety 

### ISSUE THREAD

**Issue by claudwilliams** [smooch/smooch-wordpress#19]
Hi, thanks for creating this plugin. I wanted to ask if it would be possible for the chat window to be made the priority once opened. What I mean by this is when it is opened all other features of the website are behind it. 

The reason I'm asking is because when testing the plugin on my website via a mobile phone (iPhone 5) the theme header/menu covers the top of the chat window preventing users from closing the window. 

To make things worse, app sumo share widget covers the text entry bar at the bottom of the page. I'll be removing the app sumo product however my website theme is important to my charity, so that will be remaining.

Any help would be greatly appreciated.

 
![img_1731_720](https://cloud.githubusercontent.com/assets/22867077/22044805/55318854-dd0e-11e6-9339-f7f0fc5b9d86.jpg)

![img_1730_720](https://cloud.githubusercontent.com/assets/22867077/22044806/588c525e-dd0e-11e6-9520-409cc0957c55.jpg)

**Comment by Go-Fred** [comment]
Hey @claudwilliams, the app sumo z-index CSS property is probably conflicting with ours. You can fix it by retrieving the class of their container and override their z-index property to a lower value (through custom CSS for example). Something like .class_of_the_appsumo_container{z-index:9991} should do the trick.
