### ISSUE TITLE
Smooch Settings page in wordpress

### ISSUE THREAD

**Issue by iamkarsoft** [smooch/smooch-wordpress#5]
I can't seem to locate the smooch settings page in wordpress.

**Comment by Go-Fred** [comment]
@iamkarsoft You will find it in the settings menu of Wordpress.
<img width="588" alt="screen shot 2016-04-20 at 2 18 08 pm" src="https://cloud.githubusercontent.com/assets/13648444/14685555/e87cfb30-0702-11e6-81c3-73c9b1a2edb7.png">
